### ISSUE TITLE
Helm: store.file.path does not seem to be working on NFS

### ISSUE THREAD

**Issue by samstride** [nats-io/k8s#58]
Hi,

I have attached an NFS to our k8s cluster at path `/var/mnt`

I have installed nats + stan using the latest helm charts (as of this writing) like this

```sh
helm install nats-server nats/nats --namespace=nats 

helm install stan-server nats/stan --namespace=nats \
  --set stan.nats.url=nats://nats-server:4222 \
  --set store.type=file \
  --set store.file.path=/var/mnt/nats \
  --set store.file.storageSize=1Gi
```

The startup log from stan shows the NFS path being set

```
[1] 2020/05/13 04:03:38.932852 [INF] STREAM: Starting nats-streaming-server[stan-server] version 0.17.0
[1] 2020/05/13 04:03:38.933013 [INF] STREAM: ServerID: xDec25eoUVPr0wxKKaj7xS
[1] 2020/05/13 04:03:38.933029 [INF] STREAM: Go version: go1.13.7
[1] 2020/05/13 04:03:38.933041 [INF] STREAM: Git commit: [f4b7190]
[1] 2020/05/13 04:03:38.943212 [INF] STREAM: Recovering the state...
[1] 2020/05/13 04:03:38.945227 [INF] STREAM: No recovered state
[1] 2020/05/13 04:03:39.196686 [INF] STREAM: Message store is FILE
[1] 2020/05/13 04:03:39.196697 [INF] STREAM: Store location: /var/mnt/nats
[1] 2020/05/13 04:03:39.196721 [INF] STREAM: ---------- Store Limits ----------
[1] 2020/05/13 04:03:39.196723 [INF] STREAM: Channels:                  100 *
[1] 2020/05/13 04:03:39.196725 [INF] STREAM: --------- Channels Limits --------
[1] 2020/05/13 04:03:39.196726 [INF] STREAM:   Subscriptions:          1000 *
[1] 2020/05/13 04:03:39.196727 [INF] STREAM:   Messages     :       1000000 *
[1] 2020/05/13 04:03:39.196728 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2020/05/13 04:03:39.196730 [INF] STREAM:   Age          :     unlimited *
[1] 2020/05/13 04:03:39.196731 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2020/05/13 04:03:39.196732 [INF] STREAM: ----------------------------------
[1] 2020/05/13 04:03:39.196734 [INF] STREAM: Streaming Server is ready
```

However, when I look at my NFS, `clients.dat` and `server.dat` and the subjects are being created at `/var/mnt`

I even created the folder at `/var/mnt/nats` but that didn't seem to help either. I even tried setting `securityContext` to null but that didn't work either.

Is there something I am doing wrong?

Thanks.

**Comment by wallyqs** [comment]
Thanks for filing the report, this should be fixed now via #59 

Also here is an example of how it should work now with NFS with the new `volume` declaration block:

```yaml
stan:
  replicas: 2
  nats:
    url: "nats://my-nats:4222"

store:
  type: file

  # 
  # Fault tolerance group
  # 
  ft:
    group: foo

  # 
  # File storage settings.
  # 
  file:
    path: /data/stan/store

  # volume for EFS
  volume:
    mount: /data/stan
    storageSize: 1Gi
    storageClass: aws-efs
    accessModes: ReadWriteMany
```

**Comment by samstride** [comment]
@wallyqs , I have the latest version of helm, and I did a `helm repo update`.

```sh
helm install stan-server nats/stan --namespace=nats \
  --set stan.nats.url=nats://nats-server:4222 \
  --set store.type=file \
  --set store.file.path=/var/mnt/stan/store \
  --set store.volume.mount=/var/mnt/stan \
  --set store.volume.storageSize=1Gi
```

The directory `/var/mnt/store` was created instead of `/var/mnt/stan/store`. The `stan` in the path was skipped?

However, when I uninstall and try again with fault-tolerance mode:

```sh
helm install stan-server nats/stan --namespace=nats \
  --set stan.replicas=2
  --set stan.nats.url=nats://nats-server:4222 \
  --set store.type=file \
  --set store.ft.group=stan-ft-group-1 \
  --set store.file.path=/var/mnt/stan/store \
  --set store.volume.enabled=true \
  --set store.volume.mount=/var/mnt/stan \
  --set store.volume.storageSize=1Gi \
  --set store.volume.accessModes=ReadWriteMany
```

I get this error:

```sh
kubectl logs -f stan-server-0 -n nats -c stan
Parse error on line 5: 'Expected a map value terminator "," or a map terminator "}", but got 's' instead.'
```

I cloned the repo and ran the chart locally and still the same error. Am I missing a mandatory value in FT mode?

**Comment by wallyqs** [comment]
I think the issue is that you are missing one backslash in the snippet you posted so the nats url which is required is not filled in so becoming a config error. I've also just tried with the same and I'm not getting any errors... 

```sh
helm install stan-server nats/stan \
  --set stan.replicas=2 \
  --set stan.nats.url=nats://my-nats:4222 \
  --set store.type=file \
  --set store.ft.group=stan-ft-group-1 \
  --set store.file.path=/var/mnt/stan/store \
  --set store.volume.enabled=true \
  --set store.volume.mount=/var/mnt/stan \
  --set store.volume.storageSize=100Gi \
  --set store.volume.storageClass=aws-efs \
  --set store.volume.accessModes=ReadWriteMany
```

**Comment by samstride** [comment]
@wallyqs , oh no, can't believe I missed that 😞 

Sorry, another question around FT mode. I have an on prem NFS mounted at /var/mnt/ on our on prem k8s cluster.

When I start with a fresh NFS mounted onto k8s in FT mode, I run into this situation now:

```sh
kubectl get pods -n nats
NAME              READY   STATUS    RESTARTS   AGE
nats-server-0     3/3     Running   0          41m
nats-server-box   1/1     Running   0          41m
stan-server-0     2/2     Running   0          30s
stan-server-1     0/2     Pending   0          2m13s
```

There is only 1 PV in the cluster but 2 PVC's are created `stan-server-pvc-stan-server-0` and `stan-server-pvc-stan-server-1` (I was under the impression that pods can share the 1 PVC), the standby server does not seem to start and the logs show this message:
```sh
kubectl logs -f stan-server-0 -n nats -c stan        
[1] 2020/05/28 00:42:27.178032 [INF] STREAM: Starting nats-streaming-server[stan-server] version 0.17.0
[1] 2020/05/28 00:42:27.178055 [INF] STREAM: ServerID: Ay94ZUsAjbIqsdAEmmU0uj
[1] 2020/05/28 00:42:27.178057 [INF] STREAM: Go version: go1.13.7
[1] 2020/05/28 00:42:27.178059 [INF] STREAM: Git commit: [f4b7190]
[1] 2020/05/28 00:42:27.186069 [INF] STREAM: Starting in standby mode
[1] 2020/05/28 00:42:34.673856 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
[1] 2020/05/28 00:42:42.097864 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
[1] 2020/05/28 00:42:49.521823 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
[1] 2020/05/28 00:42:56.945823 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
[1] 2020/05/28 00:43:11.793883 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
[1] 2020/05/28 00:43:34.065981 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
[1] 2020/05/28 00:44:11.185989 [INF] STREAM: ft: unable to get store lock at this time, going back to standby
```

Is there any extra steps that I need to perform for an on prem NFS solution?

Cheers.

**Comment by wallyqs** [comment]
@samstride are you able to use `--set store.volume.accessModes=ReadWriteMany` in your NFS? Fault tolerance mode requires to have a shared filesystem that supports that flag...

**Comment by samstride** [comment]
Yup, Rancher has that option:

<img width="1309" alt="Screen Shot 2020-05-28 at 6 43 43 PM" src="https://user-images.githubusercontent.com/10537580/83107969-38f12600-a113-11ea-9ec6-6194e61dcf42.png">

**Comment by wallyqs** [comment]
I see... maybe you need to set a special storage class? For example in AWS for the EFS need to set:
```
--set store.volume.storageClass=aws-efs \
```

**Comment by samstride** [comment]
@wallyqs , just to be sure, 2 PVC being created is normal? I only have 1 PV.

```
kubectl get pvc
NAME                            STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
stan-server-pvc-stan-server-0   Bound     nats-streaming   1Gi        RWX                           3m15s
stan-server-pvc-stan-server-1   Pending                                                             3m13s
```

**Comment by wallyqs** [comment]
I think so... but I'm not sure about rancher for example in efs I'm getting a pvc per pod even though they all share the same efs:
```
kubectl get pvc
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
efs                               Bound    pvc-fc5adf4b-a0b5-11ea-a784-0286c60df32e   1Mi        RWX            aws-efs        6m16s
stan-example-pvc-stan-example-0   Bound    pvc-54422d31-a0b6-11ea-9447-0a7c1e06ba6e   2Gi        RWX            aws-efs        3m49s
```

**Comment by samstride** [comment]
@wallyqs, I'm going to try a few things around FT and maybe even a clustered mode and see how things go.

I'd like to thank you for the assistance so far. Really appreciate it.

Cheers.

**Comment by samstride** [comment]
@wallyqs , hey, I finally got it to work. I have a question though, if a PVC is created per pod, how does FT work?

Example: fire up stan in FT mode with 3 replicas. This seems to create 3 PVCs. Then send a message. The subject folder is created in the corresponding PVC of the active server.  Then `kubectl delete pod stan-server-0`. `stan-server-1` is now the active server  but the subject folder in corresponding pvc for `stan-server-0` is not replicated to pvc of `stan-server-1`. Is this how it's supposed to work?

Also, if I would like to contribute to the documentation of running stan on prem with an NFS server, would it be useful and how do I go about doing it?

**Comment by samstride** [comment]
@wallyqs , PR for nfs docs submitted.

Understood, no replication in FT mode. However, when subscribers are offline and an active server is changed, messages are not being replayed since there is no replication.

- Publisher sends messages 1, 2, 3 when stan-server-0 is active
- Subscriber consumes messages 1, 2, 3 and goes offline
- Publisher sends messages 4, 5, 6 when stan-server-0 is active
- An event causes stan-server-1 to become the active server, stan-server-0 is now in standby mode.
- Subscriber comes online and does not receive messages 4, 5, 6

Am I doing something wrong during consumption or is this expected behaviour?

Thanks.
